apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bWFobm9vcg==  # encode using echo -n mahnoor | base64
  password: bXlwYXNzd29yZA==  # echo -n mypassword | base64